#!/bin/sh
# ssh-multi
# a script to ssh multiple servers over multiple tmux panes

printusage() {
    cat <<EOF
USAGE:
    $0 host [host]...
For each given host, this script creates an ssh session in a tmux pane.
The panes will be synchronized, so that they all receive the same keystrokes.
To reuse an existing tmux session, set the SSHMULTISESSION variable to the
name of that session.
EOF
}

starttmux() {
    SSHMULTISESSION=${SSHMULTISESSION:="ssh-multi-$$"}
    if [ $# -eq 0 ]; then
        printusage
        exit 1
    fi

    exec &>/dev/null # mute stdout and stderr

    if tmux has-session -t "$SSHMULTISESSION"; then
        tmux new-window -t "$SSHMULTISESSION" "ssh dukai1@$1"
    else
        tmux new-session -s "$SSHMULTISESSION" -d "ssh dukai1@$1"
    fi
    shift
    for i in $* ; do
        tmux split-window -t "$SSHMULTISESSION" -h  "ssh dukai1@$i"
        tmux select-layout -t "$SSHMULTISESSION" tiled
    done

    tmux select-pane -t "$SSHMULTISESSION:0"
    tmux set-window-option -t "$SSHMULTISESSION" synchronize-panes on
}

starttmux $*

if [ "x" != "x$TMUX" ]; then
    # we are running inside tmux
    tmux switch-client -t "$SSHMULTISESSION"
else
    # not running from inside tmux
    tmux attach-session -t "$SSHMULTISESSION"
fi
